### ISSUE TITLE
cannot start up

### ISSUE THREAD

**Issue by PaulaPaul750** [ajinabraham/CMSScan#22]
hello there,

i am not able to run the software. 
what i did:
git clone https://github.com/ajinabraham/CMSScan.git
cd CMSScan
./setup.sh
successfully.

after that, starting with ./run.sh

which gives me:
[CODE]
[2020-01-07 09:31:48 +0100] [23390] [INFO] Starting gunicorn 20.0.4
[2020-01-07 09:31:48 +0100] [23390] [INFO] Listening at: http://0.0.0.0:7070 (23390)
[2020-01-07 09:31:48 +0100] [23390] [INFO] Using worker: sync
[2020-01-07 09:31:48 +0100] [23393] [INFO] Booting worker with pid: 23393
[2020-01-07 09:31:48 +0100] [23395] [INFO] Booting worker with pid: 23395
[2020-01-07 09:31:48 +0100] [23393] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/home/administrator/hackingstuff/webapp/generell/CMSScan/venv/lib/python3.5/site-packages/gunicorn/arbiter.py", line 583, in spawn_worker
    worker.init_process()
  File "/home/administrator/hackingstuff/webapp/generell/CMSScan/venv/lib/python3.5/site-packages/gunicorn/workers/base.py", line 119, in init_process
    self.load_wsgi()
  File "/home/administrator/hackingstuff/webapp/generell/CMSScan/venv/lib/python3.5/site-packages/gunicorn/workers/base.py", line 144, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/home/administrator/hackingstuff/webapp/generell/CMSScan/venv/lib/python3.5/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/home/administrator/hackingstuff/webapp/generell/CMSScan/venv/lib/python3.5/site-packages/gunicorn/app/wsgiapp.py", line 49, in load
    return self.load_wsgiapp()
  File "/home/administrator/hackingstuff/webapp/generell/CMSScan/venv/lib/python3.5/site-packages/gunicorn/app/wsgiapp.py", line 39, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/home/administrator/hackingstuff/webapp/generell/CMSScan/venv/lib/python3.5/site-packages/gunicorn/util.py", line 358, in import_app
    mod = importlib.import_module(module)
  File "/home/administrator/hackingstuff/webapp/generell/CMSScan/venv/lib/python3.5/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 986, in _gcd_import
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 673, in exec_module
  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
  File "/home/administrator/hackingstuff/webapp/generell/CMSScan/app.py", line 7, in <module>
    from plugins.scanners import (
  File "/home/administrator/hackingstuff/webapp/generell/CMSScan/plugins/scanners.py", line 37
    print(f"[INFO] droopescan scanning URL: {url}")
                                                 ^
SyntaxError: invalid syntax
[2020-01-07 09:31:48 +0100] [23393] [INFO] Worker exiting (pid: 23393)
[2020-01-07 09:31:48 +0100] [23396] [INFO] Booting worker with pid: 23396
[2020-01-07 09:31:48 +0100] [23395] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/home/administrator/hackingstuff/webapp/generell/CMSScan/venv/lib/python3.5/site-packages/gunicorn/arbiter.py", line 583, in spawn_worker
    worker.init_process()
  File "/home/administrator/hackingstuff/webapp/generell/CMSScan/venv/lib/python3.5/site-packages/gunicorn/workers/base.py", line 119, in init_process
    self.load_wsgi()
  File "/home/administrator/hackingstuff/webapp/generell/CMSScan/venv/lib/python3.5/site-packages/gunicorn/workers/base.py", line 144, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/home/administrator/hackingstuff/webapp/generell/CMSScan/venv/lib/python3.5/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/home/administrator/hackingstuff/webapp/generell/CMSScan/venv/lib/python3.5/site-packages/gunicorn/app/wsgiapp.py", line 49, in load
    return self.load_wsgiapp()
  File "/home/administrator/hackingstuff/webapp/generell/CMSScan/venv/lib/python3.5/site-packages/gunicorn/app/wsgiapp.py", line 39, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/home/administrator/hackingstuff/webapp/generell/CMSScan/venv/lib/python3.5/site-packages/gunicorn/util.py", line 358, in import_app
    mod = importlib.import_module(module)
  File "/home/administrator/hackingstuff/webapp/generell/CMSScan/venv/lib/python3.5/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 986, in _gcd_import
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 673, in exec_module
  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
  File "/home/administrator/hackingstuff/webapp/generell/CMSScan/app.py", line 7, in <module>
    from plugins.scanners import (
  File "/home/administrator/hackingstuff/webapp/generell/CMSScan/plugins/scanners.py", line 37
    print(f"[INFO] droopescan scanning URL: {url}")
                                                 ^
SyntaxError: invalid syntax
[2020-01-07 09:31:48 +0100] [23395] [INFO] Worker exiting (pid: 23395)
[2020-01-07 09:31:48 +0100] [23396] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/home/administrator/hackingstuff/webapp/generell/CMSScan/venv/lib/python3.5/site-packages/gunicorn/arbiter.py", line 583, in spawn_worker
    worker.init_process()
  File "/home/administrator/hackingstuff/webapp/generell/CMSScan/venv/lib/python3.5/site-packages/gunicorn/workers/base.py", line 119, in init_process
    self.load_wsgi()
  File "/home/administrator/hackingstuff/webapp/generell/CMSScan/venv/lib/python3.5/site-packages/gunicorn/workers/base.py", line 144, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/home/administrator/hackingstuff/webapp/generell/CMSScan/venv/lib/python3.5/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/home/administrator/hackingstuff/webapp/generell/CMSScan/venv/lib/python3.5/site-packages/gunicorn/app/wsgiapp.py", line 49, in load
    return self.load_wsgiapp()
  File "/home/administrator/hackingstuff/webapp/generell/CMSScan/venv/lib/python3.5/site-packages/gunicorn/app/wsgiapp.py", line 39, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/home/administrator/hackingstuff/webapp/generell/CMSScan/venv/lib/python3.5/site-packages/gunicorn/util.py", line 358, in import_app
    mod = importlib.import_module(module)
  File "/home/administrator/hackingstuff/webapp/generell/CMSScan/venv/lib/python3.5/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 986, in _gcd_import
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 673, in exec_module
  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
  File "/home/administrator/hackingstuff/webapp/generell/CMSScan/app.py", line 7, in <module>
    from plugins.scanners import (
  File "/home/administrator/hackingstuff/webapp/generell/CMSScan/plugins/scanners.py", line 37
    print(f"[INFO] droopescan scanning URL: {url}")
                                                 ^
SyntaxError: invalid syntax
[2020-01-07 09:31:48 +0100] [23396] [INFO] Worker exiting (pid: 23396)
Traceback (most recent call last):
  File "/home/administrator/hackingstuff/webapp/generell/CMSScan/venv/lib/python3.5/site-packages/gunicorn/arbiter.py", line 209, in run
    self.sleep()
  File "/home/administrator/hackingstuff/webapp/generell/CMSScan/venv/lib/python3.5/site-packages/gunicorn/arbiter.py", line 357, in sleep
    ready = select.select([self.PIPE[0]], [], [], 1.0)
  File "/home/administrator/hackingstuff/webapp/generell/CMSScan/venv/lib/python3.5/site-packages/gunicorn/arbiter.py", line 242, in handle_chld
    self.reap_workers()
  File "/home/administrator/hackingstuff/webapp/generell/CMSScan/venv/lib/python3.5/site-packages/gunicorn/arbiter.py", line 525, in reap_workers
    raise HaltServer(reason, self.WORKER_BOOT_ERROR)
gunicorn.errors.HaltServer: <HaltServer 'Worker failed to boot.' 3>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/administrator/hackingstuff/webapp/generell/CMSScan/venv/bin/gunicorn", line 8, in <module>
    sys.exit(run())
  File "/home/administrator/hackingstuff/webapp/generell/CMSScan/venv/lib/python3.5/site-packages/gunicorn/app/wsgiapp.py", line 58, in run
    WSGIApplication("%(prog)s [OPTIONS] [APP_MODULE]").run()
  File "/home/administrator/hackingstuff/webapp/generell/CMSScan/venv/lib/python3.5/site-packages/gunicorn/app/base.py", line 228, in run
    super().run()
  File "/home/administrator/hackingstuff/webapp/generell/CMSScan/venv/lib/python3.5/site-packages/gunicorn/app/base.py", line 72, in run
    Arbiter(self).run()
  File "/home/administrator/hackingstuff/webapp/generell/CMSScan/venv/lib/python3.5/site-packages/gunicorn/arbiter.py", line 229, in run
    self.halt(reason=inst.reason, exit_status=inst.exit_status)
  File "/home/administrator/hackingstuff/webapp/generell/CMSScan/venv/lib/python3.5/site-packages/gunicorn/arbiter.py", line 342, in halt
    self.stop()
  File "/home/administrator/hackingstuff/webapp/generell/CMSScan/venv/lib/python3.5/site-packages/gunicorn/arbiter.py", line 393, in stop
    time.sleep(0.1)
  File "/home/administrator/hackingstuff/webapp/generell/CMSScan/venv/lib/python3.5/site-packages/gunicorn/arbiter.py", line 242, in handle_chld
    self.reap_workers()
  File "/home/administrator/hackingstuff/webapp/generell/CMSScan/venv/lib/python3.5/site-packages/gunicorn/arbiter.py", line 525, in reap_workers
    raise HaltServer(reason, self.WORKER_BOOT_ERROR)
gunicorn.errors.HaltServer: <HaltServer 'Worker failed to boot.' 3>
[/CODE]

**Comment by ajinabraham** [comment]
# Requires ruby, ruby-dev, gem, libwww-perl, python3.6+ and git
