### ISSUE TITLE
not able to install 

### ISSUE THREAD

**Issue by kaal-kali** [ajinabraham/CMSScan#24]
./setup.sh 
Fetching: mini_portile2-2.4.0.gem (100%)
Successfully installed mini_portile2-2.4.0
Fetching: nokogiri-1.10.9.gem (100%)
Building native extensions. This could take a while...
ERROR:  Error installing wpscan:
        ERROR: Failed to build gem native extension.

    current directory: /var/lib/gems/2.5.0/gems/nokogiri-1.10.9/ext/nokogiri
/usr/bin/ruby2.5 -r ./siteconf20200704-7424-1p6wrj6.rb extconf.rb
checking if the C compiler accepts ... yes
Building nokogiri using packaged libraries.
Using mini_portile version 2.4.0
checking for gzdopen() in -lz... no
zlib is missing; necessary for building libxml2
*** extconf.rb failed ***
Could not create Makefile due to some reason, probably lack of necessary
libraries and/or headers.  Check the mkmf.log file for more details.  You may
need configuration options.

Provided configuration options:
        --with-opt-dir
        --without-opt-dir
        --with-opt-include
        --without-opt-include=${opt-dir}/include
        --with-opt-lib
        --without-opt-lib=${opt-dir}/lib
        --with-make-prog
        --without-make-prog
        --srcdir=.
        --curdir
        --ruby=/usr/bin/$(RUBY_BASE_NAME)2.5
        --help
        --clean
        --use-system-libraries
        --enable-static
        --disable-static
        --with-zlib-dir
        --without-zlib-dir
        --with-zlib-include
        --without-zlib-include=${zlib-dir}/include
        --with-zlib-lib
        --without-zlib-lib=${zlib-dir}/lib
        --enable-cross-build
        --disable-cross-build

To see why this extension failed to compile, please check the mkmf.log which can be found here:

  /var/lib/gems/2.5.0/extensions/x86_64-linux/2.5.0/nokogiri-1.10.9/mkmf.log

extconf failed, exit code 1

Gem files will remain installed in /var/lib/gems/2.5.0/gems/nokogiri-1.10.9 for inspection.
Results logged to /var/lib/gems/2.5.0/extensions/x86_64-linux/2.5.0/nokogiri-1.10.9/gem_make.out
Traceback (most recent call last):
        12: from /usr/bin/wpscan:23:in `<main>'
        11: from /usr/lib/ruby/2.5.0/rubygems.rb:304:in `activate_bin_path'
        10: from /usr/lib/ruby/2.5.0/rubygems.rb:304:in `synchronize'
         9: from /usr/lib/ruby/2.5.0/rubygems.rb:305:in `block in activate_bin_path'
         8: from /usr/lib/ruby/2.5.0/rubygems/specification.rb:1440:in `activate'
         7: from /usr/lib/ruby/2.5.0/rubygems/specification.rb:1458:in `activate_dependencies'
         6: from /usr/lib/ruby/2.5.0/rubygems/specification.rb:1458:in `each'
         5: from /usr/lib/ruby/2.5.0/rubygems/specification.rb:1472:in `block in activate_dependencies'
         4: from /usr/lib/ruby/2.5.0/rubygems/specification.rb:1440:in `activate'
         3: from /usr/lib/ruby/2.5.0/rubygems/specification.rb:1458:in `activate_dependencies'
         2: from /usr/lib/ruby/2.5.0/rubygems/specification.rb:1458:in `each'
         1: from /usr/lib/ruby/2.5.0/rubygems/specification.rb:1469:in `block in activate_dependencies'
/usr/lib/ruby/2.5.0/rubygems/dependency.rb:312:in `to_specs': Could not find 'nokogiri' (~> 1.10.8) - did find: [nokogiri-1.10.4] (Gem::MissingSpecVersionError)
Checked in 'GEM_PATH=/root/.gem/ruby/2.5.0:/var/lib/gems/2.5.0:/usr/lib/ruby/gems/2.5.0:/usr/share/rubygems-integration/2.5.0:/usr/share/rubygems-integration/all:/usr/lib/x86_64-linux-gnu/rubygems-integration/2.5.0', execute `gem env` for more information
/usr/bin/python3: No module named pip
./setup.sh: 9: virtualenv: not found
./setup.sh: 10: .: Can't open venv/bin/activate

**Comment by ajinabraham** [comment]
You need to install the missing libs.
`zlib is missing; necessary for building libxml2`

I suggest, you use the docker image instead.

**Comment by kaal-kali** [comment]
Would u please help me in detail what command I'll run step bcz I am a
beginner

**Comment by kaal-kali** [comment]
after installing zlib its show  /usr/bin/python3: No module named pip
./setup.sh: 9: virtualenv: not found
./setup.sh: 10: .: Can't open venv/bin/activate

**Comment by kaal-kali** [comment]
root@bunty:~/Desktop/CMSScan# ./run.sh 
[2020-07-05 01:17:35 +0530] [16643] [INFO] Starting gunicorn 20.0.4
[2020-07-05 01:17:35 +0530] [16643] [INFO] Listening at: http://0.0.0.0:7070 (16643)
[2020-07-05 01:17:35 +0530] [16643] [INFO] Using worker: sync
[2020-07-05 01:17:35 +0530] [16645] [INFO] Booting worker with pid: 16645
[2020-07-05 01:17:35 +0530] [16646] [INFO] Booting worker with pid: 16646
[2020-07-05 01:17:35 +0530] [16647] [INFO] Booting worker with pid: 16647
[INFO] Updating WPScan
[INFO] Updating WPScan
[INFO] Updating WPScan

not working anything

**Comment by kaal-kali** [comment]
now its show retrying  cant connect to 0.0.0.0. something

**Comment by kaal-kali** [comment]
[2020-07-05 22:58:42 +0530] [4670] [INFO] Starting gunicorn 20.0.4
[2020-07-05 22:58:42 +0530] [4670] [ERROR] Connection in use: ('0.0.0.0', 7070)
[2020-07-05 22:58:42 +0530] [4670] [ERROR] Retrying in 1 second.
[2020-07-05 22:58:43 +0530] [4670] [ERROR] Connection in use: ('0.0.0.0', 7070)
[2020-07-05 22:58:43 +0530] [4670] [ERROR] Retrying in 1 second.
[2020-07-05 22:58:44 +0530] [4670] [ERROR] Connection in use: ('0.0.0.0', 7070)
[2020-07-05 22:58:44 +0530] [4670] [ERROR] Retrying in 1 second.
[2020-07-05 22:58:45 +0530] [4670] [ERROR] Connection in use: ('0.0.0.0', 7070)
[2020-07-05 22:58:45 +0530] [4670] [ERROR] Retrying in 1 second.
[2020-07-05 22:58:46 +0530] [4670] [ERROR] Connection in use: ('0.0.0.0', 7070)
[2020-07-05 22:58:46 +0530] [4670] [ERROR] Retrying in 1 second.
[2020-07-05 22:58:47 +0530] [4670] [ERROR] Can't connect to ('0.0.0.0', 7070)

**Comment by ajinabraham** [comment]
This is because something else is already using that port. you need to find and kill what's using that port or do a restart.

**Comment by kaal-kali** [comment]
[2020-07-05 22:58:42 +0530] [4670] [INFO] Starting gunicorn 20.0.4
[2020-07-05 22:58:42 +0530] [4670] [ERROR] Connection in use: ('0.0.0.0', 7070)
[2020-07-05 22:58:42 +0530] [4670] [ERROR] Retrying in 1 second.
[2020-07-05 22:58:43 +0530] [4670] [ERROR] Connection in use: ('0.0.0.0', 7070)
[2020-07-05 22:58:43 +0530] [4670] [ERROR] Retrying in 1 second.
[2020-07-05 22:58:44 +0530] [4670] [ERROR] Connection in use: ('0.0.0.0', 7070)
[2020-07-05 22:58:44 +0530] [4670] [ERROR] Retrying in 1 second.
[2020-07-05 22:58:45 +0530] [4670] [ERROR] Connection in use: ('0.0.0.0', 7070)
[2020-07-05 22:58:45 +0530] [4670] [ERROR] Retrying in 1 second.
[2020-07-05 22:58:46 +0530] [4670] [ERROR] Connection in use: ('0.0.0.0', 7070)
[2020-07-05 22:58:46 +0530] [4670] [ERROR] Retrying in 1 second.
[2020-07-05 22:58:47 +0530] [4670] [ERROR] Can't connect to ('0.0.0.0', 7070)

**Comment by kaal-kali** [comment]
now its again show 

nty:~/CMSScan# ./run.sh 
[2020-07-06 07:50:18 +0530] [3090] [INFO] Starting gunicorn 20.0.4
[2020-07-06 07:50:18 +0530] [3090] [INFO] Listening at: http://0.0.0.0:7070 (3090)
[2020-07-06 07:50:18 +0530] [3090] [INFO] Using worker: sync
[2020-07-06 07:50:18 +0530] [3092] [INFO] Booting worker with pid: 3092
[2020-07-06 07:50:18 +0530] [3093] [INFO] Booting worker with pid: 3093
[2020-07-06 07:50:18 +0530] [3094] [INFO] Booting worker with pid: 3094
[INFO] Updating WPScan
[INFO] Updating WPScan
[INFO] Updating WPScan

please sr help me out for this problem not showing any issue what will i do

**Comment by akhiljain029** [comment]
I am getting the same issue.
2020-08-12 19:12:30 +0530] [3335] [INFO] Starting gunicorn 20.0.4
[2020-08-12 19:12:30 +0530] [3335] [INFO] Listening at: http://0.0.0.0:7070 (3335)
[2020-08-12 19:12:30 +0530] [3335] [INFO] Using worker: sync
[2020-08-12 19:12:30 +0530] [3337] [INFO] Booting worker with pid: 3337
[2020-08-12 19:12:30 +0530] [3338] [INFO] Booting worker with pid: 3338
[2020-08-12 19:12:30 +0530] [3339] [INFO] Booting worker with pid: 3339
[INFO] Updating WPScan
[INFO] Updating WPScan
[INFO] Updating WPScan
