### ISSUE TITLE
Syntax errors (?)

### ISSUE THREAD

**Issue by DBX12** [ajinabraham/CMSScan#4]
The setup.sh exited successfully with exit code 0, Running run.sh however fails with a syntax error.
I'm not very good with Python, so I hope you can help, the log is attached:

```
[2018-11-19 08:51:11 +0100] [28287] [INFO] Starting gunicorn 19.9.0
[2018-11-19 08:51:11 +0100] [28287] [INFO] Listening at: http://0.0.0.0:7070 (28287)
[2018-11-19 08:51:11 +0100] [28287] [INFO] Using worker: sync
[2018-11-19 08:51:11 +0100] [28294] [INFO] Booting worker with pid: 28294
[2018-11-19 08:51:11 +0100] [28296] [INFO] Booting worker with pid: 28296
[2018-11-19 08:51:11 +0100] [28294] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/tmp/CMSScan/venv/lib/python3.5/site-packages/gunicorn/arbiter.py", line 583, in spawn_worker
    worker.init_process()
  File "/tmp/CMSScan/venv/lib/python3.5/site-packages/gunicorn/workers/base.py", line 129, in init_process
    self.load_wsgi()
  File "/tmp/CMSScan/venv/lib/python3.5/site-packages/gunicorn/workers/base.py", line 138, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/tmp/CMSScan/venv/lib/python3.5/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/tmp/CMSScan/venv/lib/python3.5/site-packages/gunicorn/app/wsgiapp.py", line 52, in load
    return self.load_wsgiapp()
  File "/tmp/CMSScan/venv/lib/python3.5/site-packages/gunicorn/app/wsgiapp.py", line 41, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/tmp/CMSScan/venv/lib/python3.5/site-packages/gunicorn/util.py", line 350, in import_app
    __import__(module)
  File "/tmp/CMSScan/app.py", line 6, in <module>
    from plugins.scanners import (
  File "/tmp/CMSScan/plugins/scanners.py", line 37
    print(f"[INFO] droopescan scanning URL: {url}")
                                                 ^
SyntaxError: invalid syntax
[2018-11-19 08:51:11 +0100] [28294] [INFO] Worker exiting (pid: 28294)
[2018-11-19 08:51:11 +0100] [28297] [INFO] Booting worker with pid: 28297
[2018-11-19 08:51:11 +0100] [28296] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/tmp/CMSScan/venv/lib/python3.5/site-packages/gunicorn/arbiter.py", line 583, in spawn_worker
    worker.init_process()
  File "/tmp/CMSScan/venv/lib/python3.5/site-packages/gunicorn/workers/base.py", line 129, in init_process
    self.load_wsgi()
  File "/tmp/CMSScan/venv/lib/python3.5/site-packages/gunicorn/workers/base.py", line 138, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/tmp/CMSScan/venv/lib/python3.5/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/tmp/CMSScan/venv/lib/python3.5/site-packages/gunicorn/app/wsgiapp.py", line 52, in load
    return self.load_wsgiapp()
  File "/tmp/CMSScan/venv/lib/python3.5/site-packages/gunicorn/app/wsgiapp.py", line 41, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/tmp/CMSScan/venv/lib/python3.5/site-packages/gunicorn/util.py", line 350, in import_app
    __import__(module)
  File "/tmp/CMSScan/app.py", line 6, in <module>
    from plugins.scanners import (
  File "/tmp/CMSScan/plugins/scanners.py", line 37
    print(f"[INFO] droopescan scanning URL: {url}")
                                                 ^
SyntaxError: invalid syntax
[2018-11-19 08:51:11 +0100] [28296] [INFO] Worker exiting (pid: 28296)
[2018-11-19 08:51:11 +0100] [28297] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/tmp/CMSScan/venv/lib/python3.5/site-packages/gunicorn/arbiter.py", line 583, in spawn_worker
    worker.init_process()
  File "/tmp/CMSScan/venv/lib/python3.5/site-packages/gunicorn/workers/base.py", line 129, in init_process
    self.load_wsgi()
  File "/tmp/CMSScan/venv/lib/python3.5/site-packages/gunicorn/workers/base.py", line 138, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/tmp/CMSScan/venv/lib/python3.5/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/tmp/CMSScan/venv/lib/python3.5/site-packages/gunicorn/app/wsgiapp.py", line 52, in load
    return self.load_wsgiapp()
  File "/tmp/CMSScan/venv/lib/python3.5/site-packages/gunicorn/app/wsgiapp.py", line 41, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/tmp/CMSScan/venv/lib/python3.5/site-packages/gunicorn/util.py", line 350, in import_app
    __import__(module)
  File "/tmp/CMSScan/app.py", line 6, in <module>
    from plugins.scanners import (
  File "/tmp/CMSScan/plugins/scanners.py", line 37
    print(f"[INFO] droopescan scanning URL: {url}")
                                                 ^
SyntaxError: invalid syntax
[2018-11-19 08:51:11 +0100] [28297] [INFO] Worker exiting (pid: 28297)
Traceback (most recent call last):
  File "/tmp/CMSScan/venv/lib/python3.5/site-packages/gunicorn/arbiter.py", line 203, in run
    self.manage_workers()
  File "/tmp/CMSScan/venv/lib/python3.5/site-packages/gunicorn/arbiter.py", line 545, in manage_workers
    self.spawn_workers()
  File "/tmp/CMSScan/venv/lib/python3.5/site-packages/gunicorn/arbiter.py", line 617, in spawn_workers
    time.sleep(0.1 * random.random())
  File "/tmp/CMSScan/venv/lib/python3.5/site-packages/gunicorn/arbiter.py", line 245, in handle_chld
    self.reap_workers()
  File "/tmp/CMSScan/venv/lib/python3.5/site-packages/gunicorn/arbiter.py", line 525, in reap_workers
    raise HaltServer(reason, self.WORKER_BOOT_ERROR)
gunicorn.errors.HaltServer: <HaltServer 'Worker failed to boot.' 3>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/tmp/CMSScan/venv/bin/gunicorn", line 11, in <module>
    sys.exit(run())
  File "/tmp/CMSScan/venv/lib/python3.5/site-packages/gunicorn/app/wsgiapp.py", line 61, in run
    WSGIApplication("%(prog)s [OPTIONS] [APP_MODULE]").run()
  File "/tmp/CMSScan/venv/lib/python3.5/site-packages/gunicorn/app/base.py", line 223, in run
    super(Application, self).run()
  File "/tmp/CMSScan/venv/lib/python3.5/site-packages/gunicorn/app/base.py", line 72, in run
    Arbiter(self).run()
  File "/tmp/CMSScan/venv/lib/python3.5/site-packages/gunicorn/arbiter.py", line 232, in run
    self.halt(reason=inst.reason, exit_status=inst.exit_status)
  File "/tmp/CMSScan/venv/lib/python3.5/site-packages/gunicorn/arbiter.py", line 345, in halt
    self.stop()
  File "/tmp/CMSScan/venv/lib/python3.5/site-packages/gunicorn/arbiter.py", line 393, in stop
    time.sleep(0.1)
  File "/tmp/CMSScan/venv/lib/python3.5/site-packages/gunicorn/arbiter.py", line 245, in handle_chld
    self.reap_workers()
  File "/tmp/CMSScan/venv/lib/python3.5/site-packages/gunicorn/arbiter.py", line 525, in reap_workers
    raise HaltServer(reason, self.WORKER_BOOT_ERROR)
gunicorn.errors.HaltServer: <HaltServer 'Worker failed to boot.' 3>
```

**Comment by ajinabraham** [comment]
Use python 3. 6 or above. Looks like f'{} ' not supported in 3.5 I think.
